version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - n8n_data:/home/node/.n8n

  whatsapp-bot:
    build: .
    volumes:
      - ./session:/app/session
    depends_on:
      - n8n
    network_mode: service:n8n  # share network with n8n so it can access localhost:n8n
    environment:
      - NODE_ENV=production

volumes:
  n8n_data:
