version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - n8n_data:/home/node/.n8n

  whatsapp-bot:
    build: .
    volumes:
      - ./bot:/app/bot
      - ./session:/app/session
    working_dir: /app/bot
    command: npx nodemon index.js
    depends_on:
      - n8n
    network_mode: service:n8n
    environment:
      - NODE_ENV=production

volumes:
  n8n_data:
