version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nursebot
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: therapydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - COHERE_API_KEY=${COHERE_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db

  whatsapp-bot:
    build: .
    volumes:
      - ./bot:/app/bot
      - ./session:/app/session
    working_dir: /app/bot
    command: npx nodemon index.js
    depends_on:
      - n8n
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=nursebot
      - DB_PASSWORD=secret
      - DB_NAME=therapydb
    network_mode: service:n8n

volumes:
  n8n_data:
  db_data:
